PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>
PREFIX wotsec: <https://www.w3.org/2019/wot/security#>
PREFIX htv: <http://www.w3.org/2011/http#>
PREFIX hctl: <https://www.w3.org/2019/wot/hypermedia#>
PREFIX js: <https://www.w3.org/2019/wot/json-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-karim#>
    {
        ?farm hmas:contains ?section1.
        ?farm hmas:contains ?section2.
        ?farm hmas:contains ?section3.
        ?farm hmas:contains ?section4.
        ?section1 a td:Thing, was:Section;
  			td:title "A section of land";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];
  			td:hasBase <http://localhost:1080/api/sections/1/>;
        ?section2 a td:Thing, was:Section;
  			td:title "A section of land";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];
  			td:hasBase <http://localhost:1080/api/sections/2/>;
        ?section3 a td:Thing, was:Section;
  			td:title "A section of land";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];
  			td:hasBase <http://localhost:1080/api/sections/3/>;
        ?section4 a td:Thing, was:Section;
  			td:title "A section of land";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];
  			td:hasBase <http://localhost:1080/api/sections/4/>;
    
        
    }.
} WHERE {
	?farm a was:Farm.
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-karim#section-", strUUID())) AS ?newSection1)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-karim#section-", strUUID())) AS ?newSection2)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-karim#section-", strUUID())) AS ?newSection3)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-karim#section-", strUUID())) AS ?newSection4)
}
